//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAMS()
        {
            this.TASKS = new HashSet<TASKS>();
            this.TEAM_ANNOUNCEMENTS = new HashSet<TEAM_ANNOUNCEMENTS>();
            this.TEAM_MEMBERS = new HashSet<TEAM_MEMBERS>();
        }
    
        public int TEAMID { get; set; }
        public int DEPREF { get; set; }
        public string TEAM_DEF { get; set; }
        public string TEAM_NAME { get; set; }
    
        public virtual DEPARTMENTS DEPARTMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKS> TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_ANNOUNCEMENTS> TEAM_ANNOUNCEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_MEMBERS> TEAM_MEMBERS { get; set; }
    }
}
