//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM_ANNOUNCEMENTS
    {
        public int ANNID { get; set; }
        public int OWNER_ID { get; set; }
        public int TEAM_ID { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public System.DateTime DEADLINE { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
    
        public virtual TEAMS TEAMS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
