//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.COMPANY_ANNOUNCEMENTS = new HashSet<COMPANY_ANNOUNCEMENTS>();
            this.DEPARTMENT_ANNOUNCEMENTS = new HashSet<DEPARTMENT_ANNOUNCEMENTS>();
            this.PERSONAL_TASKS = new HashSet<PERSONAL_TASKS>();
            this.TASKS = new HashSet<TASKS>();
            this.TEAM_ANNOUNCEMENTS = new HashSet<TEAM_ANNOUNCEMENTS>();
            this.TEAM_MEMBERS = new HashSet<TEAM_MEMBERS>();
            this.USER_CONTACT_INFO = new HashSet<USER_CONTACT_INFO>();
            this.USER_ROLES = new HashSet<USER_ROLES>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PW_KEY { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public bool IS_ADMIN { get; set; }
        public short STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY_ANNOUNCEMENTS> COMPANY_ANNOUNCEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTMENT_ANNOUNCEMENTS> DEPARTMENT_ANNOUNCEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAL_TASKS> PERSONAL_TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKS> TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_ANNOUNCEMENTS> TEAM_ANNOUNCEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_MEMBERS> TEAM_MEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_CONTACT_INFO> USER_CONTACT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ROLES> USER_ROLES { get; set; }
    }
}
