//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DEPARTMENTS
    {
        public int DEPID { get; set; }
        public int COMPREF { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string DEPARTMENT_DEF { get; set; }
        public int TEAMID { get; set; }
        public string TEAM_DEF { get; set; }
        public string TEAM_NAME { get; set; }
    }
}
