//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PERSONAL_TASKS
    {
        public int TASKID { get; set; }
        public int USERREF { get; set; }
        public string USERNAME { get; set; }
        public string TASK_TITLE { get; set; }
        public string TASK_DESCRIPTION { get; set; }
        public short STATUS { get; set; }
    }
}
