//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TEAMS
    {
        public string TEAM_NAME { get; set; }
        public string TEAM_DEF { get; set; }
        public string USERNAME { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public int ROLE { get; set; }
        public int TEAMID { get; set; }
        public int USERID { get; set; }
        public int DEPREF { get; set; }
    }
}
