//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USERS_DETAILED
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public bool IS_ADMIN { get; set; }
        public short STATUS { get; set; }
        public string PHONE { get; set; }
        public string MAIL { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string POSTAL_CODE { get; set; }
        public string OPEN_ADRESS { get; set; }
    }
}
